package com.researchspace.api.examples.java;

import org.junit.Test;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Sarah' at '12/16/16 12:14 AM' with Gradle 3.0
 *
 * @author Sarah, @date 12/16/16 12:14 AM
 */
public class LibraryTest {
	
    @Test 
    public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        //assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
