package com.researchspace.api.examples.java;

import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Sarah' at '12/16/16 12:14 AM' with Gradle 3.0
 *
 * @author Sarah, @date 12/16/16 12:14 AM
 */
public class Library {
	
	public static final String API_DOCUMENTS_ENDPOINT = "/api/v1/documents"; 
	
	public static String getAPIDocumentsUrl() {
		return getConfigProperty("serverURL") + API_DOCUMENTS_ENDPOINT;
	}
	
	public static String getAPIDocumentUrl(long docID) {
		return getAPIDocumentsUrl() + "/" + docID;
	}
	
	//Method to set property (API key or host URL) from input file
	public static String getConfigProperty(String property) {
		Properties prop = new Properties();
		InputStream input = null;
		String propertyValue = "";
	
		try {
			input = new FileInputStream("config.properties");
			// load a properties file
			prop.load(input);
			// get the property value and print it out
			propertyValue = prop.getProperty(property);
		} catch (IOException ex) {
			ex.printStackTrace();
		} finally {
			if (input != null) {
				try {
					input.close();
				} catch (IOException e) {
					e.printStackTrace();
				}
			}
		}
		return propertyValue;
	}

}
