/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Sarah' at '12/16/16 12:14 AM' with Gradle 3.0
 *
 * @author Sarah, @date 12/16/16 12:14 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
